name = "spark_rfsb509_experimental"
description = "Collection of verified SPARK 2014 experimental RFSB509 implementations"
long-description = "A collection of silver-level SPARK 2014 verified RFSB509 implementations, that deviate from the original specifications. This is for research only."
version = "0.1.0-dev"
tags = ["spark", "cryptography", "security", "rfsb509"]
licenses = "BSD-3-Clause"
website = "https://github.com/MxAR/spark-rfsb509-experimential"

authors = ["Max A. Scheven"]
maintainers = ["Max A. Scheven <max.arthur@scheven-office.com>"]
maintainers-logins = ["mxar"]

[[depends-on]]
gnat_external = ">=13.2.1"
[[depends-on]]
sparknacl = "^3.0.0"

[gpr-externals]
SPARKNACL_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]
SPARKNACL_COMPILE_CHECKS = ["enabled", "disabled"]
SPARKNACL_RUNTIME_CHECKS = ["enabled", "disabled"]
SPARKNACL_STYLE_CHECKS = ["enabled", "disabled"]
SPARKNACL_CONTRACTS = ["enabled", "disabled"]
SPARKNACL_BUILD_MODE = ["debug", "O1", "O2", "O3", "Os"]
